env:
  es6: true
  node: true
extends: 'eslint:recommended'
plugins:
  - mocha
rules:
  indent: [ error, 4 ]
  linebreak-style: [ error, unix ]
  mocha/handle-done-callback: error
  mocha/max-top-level-suites: [ error, { limit: 1 } ]
  mocha/no-exclusive-tests: error
  mocha/no-global-tests: error
  mocha/no-identical-title: error
  mocha/no-mocha-arrows: error
  mocha/no-nested-tests: error
  mocha/no-pending-tests: error
  mocha/no-return-and-callback: error
  mocha/no-sibling-hooks: error
  mocha/no-top-level-hooks: error
  quotes: [ error, single ]
  semi: [ error, always ]
