# from https://github.com/screwdriver-cd-test/quickstart-nodejs/blob/master/screwdriver.yaml
---
#### doesn't work yet
#   workflow:
#       - publish
shared:
    image: node:6
jobs:
    main:
        steps:
            - install-deps: npm install
            - run-tests: npm run-script test
#### doesn't work yet
#   publish:
#       secrets:
#           - GIT_KEY       # so we can `git push`
#           - NPM_TOKEN     # so we can `npm publish`
#       steps:
#           - set-access: npm config set access public > /dev/null 2>&1
#           - set-token: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN > /dev/null 2>&1
#           - bump-version: ./ci/bump-version.sh
#           - push-git: ./ci/git-ssh.sh && ./ci/git-push.sh
#           - publish-npm: npm publish
